name: CI

on: 
  push:
    paths-ignore:
        - '.gitignore'
        - 'LICENSE'
        - 'README*'
  pull_request:
    paths-ignore:
        - '.gitignore'
        - 'LICENSE'
        - 'README*'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 1
      
      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm install
          
      - name: Build and package
        run: npm run make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-${{ matrix.os }}
          path: dist_electron
